[package]
name = "chippy_crab"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.7"
<<<<<<< HEAD
bevy_rapier2d = "*"
=======
bevy_rapier2d = { version = "*", features = [ "simd-stable", "debug-render" ] }
>>>>>>> origin/HEAD
rand = "0.8"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
